/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as AuthDashboardImport } from './routes/_auth.dashboard'
import { Route as AuthItemsListImport } from './routes/_auth.items.list'
import { Route as AuthItemsCreateImport } from './routes/_auth.items.create'
import { Route as AuthItemsEditItemIdImport } from './routes/_auth.items.edit.$itemId'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthDashboardRoute = AuthDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)

const AuthItemsListRoute = AuthItemsListImport.update({
  id: '/items/list',
  path: '/items/list',
  getParentRoute: () => AuthRoute,
} as any)

const AuthItemsCreateRoute = AuthItemsCreateImport.update({
  id: '/items/create',
  path: '/items/create',
  getParentRoute: () => AuthRoute,
} as any)

const AuthItemsEditItemIdRoute = AuthItemsEditItemIdImport.update({
  id: '/items/edit/$itemId',
  path: '/items/edit/$itemId',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardImport
      parentRoute: typeof AuthImport
    }
    '/_auth/items/create': {
      id: '/_auth/items/create'
      path: '/items/create'
      fullPath: '/items/create'
      preLoaderRoute: typeof AuthItemsCreateImport
      parentRoute: typeof AuthImport
    }
    '/_auth/items/list': {
      id: '/_auth/items/list'
      path: '/items/list'
      fullPath: '/items/list'
      preLoaderRoute: typeof AuthItemsListImport
      parentRoute: typeof AuthImport
    }
    '/_auth/items/edit/$itemId': {
      id: '/_auth/items/edit/$itemId'
      path: '/items/edit/$itemId'
      fullPath: '/items/edit/$itemId'
      preLoaderRoute: typeof AuthItemsEditItemIdImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthItemsCreateRoute: typeof AuthItemsCreateRoute
  AuthItemsListRoute: typeof AuthItemsListRoute
  AuthItemsEditItemIdRoute: typeof AuthItemsEditItemIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthItemsCreateRoute: AuthItemsCreateRoute,
  AuthItemsListRoute: AuthItemsListRoute,
  AuthItemsEditItemIdRoute: AuthItemsEditItemIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthDashboardRoute
  '/items/create': typeof AuthItemsCreateRoute
  '/items/list': typeof AuthItemsListRoute
  '/items/edit/$itemId': typeof AuthItemsEditItemIdRoute
}

export interface FileRoutesByTo {
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthDashboardRoute
  '/items/create': typeof AuthItemsCreateRoute
  '/items/list': typeof AuthItemsListRoute
  '/items/edit/$itemId': typeof AuthItemsEditItemIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/items/create': typeof AuthItemsCreateRoute
  '/_auth/items/list': typeof AuthItemsListRoute
  '/_auth/items/edit/$itemId': typeof AuthItemsEditItemIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/dashboard'
    | '/items/create'
    | '/items/list'
    | '/items/edit/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/login'
    | '/dashboard'
    | '/items/create'
    | '/items/list'
    | '/items/edit/$itemId'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/dashboard'
    | '/_auth/items/create'
    | '/_auth/items/list'
    | '/_auth/items/edit/$itemId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/login"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/dashboard",
        "/_auth/items/create",
        "/_auth/items/list",
        "/_auth/items/edit/$itemId"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_auth/dashboard": {
      "filePath": "_auth.dashboard.tsx",
      "parent": "/_auth"
    },
    "/_auth/items/create": {
      "filePath": "_auth.items.create.tsx",
      "parent": "/_auth"
    },
    "/_auth/items/list": {
      "filePath": "_auth.items.list.tsx",
      "parent": "/_auth"
    },
    "/_auth/items/edit/$itemId": {
      "filePath": "_auth.items.edit.$itemId.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
