/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as AuthDashboardImport } from './routes/_auth.dashboard'
import { Route as AuthSalesListImport } from './routes/_auth.sales.list'
import { Route as AuthSalesCreateImport } from './routes/_auth.sales.create'
import { Route as AuthProductsListImport } from './routes/_auth.products.list'
import { Route as AuthProductsCreateImport } from './routes/_auth.products.create'
import { Route as AuthItemsListImport } from './routes/_auth.items.list'
import { Route as AuthItemsCreateImport } from './routes/_auth.items.create'
import { Route as AuthProductsEditProductIdImport } from './routes/_auth.products.edit.$productId'
import { Route as AuthItemsEditItemIdImport } from './routes/_auth.items.edit.$itemId'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthDashboardRoute = AuthDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSalesListRoute = AuthSalesListImport.update({
  id: '/sales/list',
  path: '/sales/list',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSalesCreateRoute = AuthSalesCreateImport.update({
  id: '/sales/create',
  path: '/sales/create',
  getParentRoute: () => AuthRoute,
} as any)

const AuthProductsListRoute = AuthProductsListImport.update({
  id: '/products/list',
  path: '/products/list',
  getParentRoute: () => AuthRoute,
} as any)

const AuthProductsCreateRoute = AuthProductsCreateImport.update({
  id: '/products/create',
  path: '/products/create',
  getParentRoute: () => AuthRoute,
} as any)

const AuthItemsListRoute = AuthItemsListImport.update({
  id: '/items/list',
  path: '/items/list',
  getParentRoute: () => AuthRoute,
} as any)

const AuthItemsCreateRoute = AuthItemsCreateImport.update({
  id: '/items/create',
  path: '/items/create',
  getParentRoute: () => AuthRoute,
} as any)

const AuthProductsEditProductIdRoute = AuthProductsEditProductIdImport.update({
  id: '/products/edit/$productId',
  path: '/products/edit/$productId',
  getParentRoute: () => AuthRoute,
} as any)

const AuthItemsEditItemIdRoute = AuthItemsEditItemIdImport.update({
  id: '/items/edit/$itemId',
  path: '/items/edit/$itemId',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardImport
      parentRoute: typeof AuthImport
    }
    '/_auth/items/create': {
      id: '/_auth/items/create'
      path: '/items/create'
      fullPath: '/items/create'
      preLoaderRoute: typeof AuthItemsCreateImport
      parentRoute: typeof AuthImport
    }
    '/_auth/items/list': {
      id: '/_auth/items/list'
      path: '/items/list'
      fullPath: '/items/list'
      preLoaderRoute: typeof AuthItemsListImport
      parentRoute: typeof AuthImport
    }
    '/_auth/products/create': {
      id: '/_auth/products/create'
      path: '/products/create'
      fullPath: '/products/create'
      preLoaderRoute: typeof AuthProductsCreateImport
      parentRoute: typeof AuthImport
    }
    '/_auth/products/list': {
      id: '/_auth/products/list'
      path: '/products/list'
      fullPath: '/products/list'
      preLoaderRoute: typeof AuthProductsListImport
      parentRoute: typeof AuthImport
    }
    '/_auth/sales/create': {
      id: '/_auth/sales/create'
      path: '/sales/create'
      fullPath: '/sales/create'
      preLoaderRoute: typeof AuthSalesCreateImport
      parentRoute: typeof AuthImport
    }
    '/_auth/sales/list': {
      id: '/_auth/sales/list'
      path: '/sales/list'
      fullPath: '/sales/list'
      preLoaderRoute: typeof AuthSalesListImport
      parentRoute: typeof AuthImport
    }
    '/_auth/items/edit/$itemId': {
      id: '/_auth/items/edit/$itemId'
      path: '/items/edit/$itemId'
      fullPath: '/items/edit/$itemId'
      preLoaderRoute: typeof AuthItemsEditItemIdImport
      parentRoute: typeof AuthImport
    }
    '/_auth/products/edit/$productId': {
      id: '/_auth/products/edit/$productId'
      path: '/products/edit/$productId'
      fullPath: '/products/edit/$productId'
      preLoaderRoute: typeof AuthProductsEditProductIdImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthItemsCreateRoute: typeof AuthItemsCreateRoute
  AuthItemsListRoute: typeof AuthItemsListRoute
  AuthProductsCreateRoute: typeof AuthProductsCreateRoute
  AuthProductsListRoute: typeof AuthProductsListRoute
  AuthSalesCreateRoute: typeof AuthSalesCreateRoute
  AuthSalesListRoute: typeof AuthSalesListRoute
  AuthItemsEditItemIdRoute: typeof AuthItemsEditItemIdRoute
  AuthProductsEditProductIdRoute: typeof AuthProductsEditProductIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthItemsCreateRoute: AuthItemsCreateRoute,
  AuthItemsListRoute: AuthItemsListRoute,
  AuthProductsCreateRoute: AuthProductsCreateRoute,
  AuthProductsListRoute: AuthProductsListRoute,
  AuthSalesCreateRoute: AuthSalesCreateRoute,
  AuthSalesListRoute: AuthSalesListRoute,
  AuthItemsEditItemIdRoute: AuthItemsEditItemIdRoute,
  AuthProductsEditProductIdRoute: AuthProductsEditProductIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthDashboardRoute
  '/items/create': typeof AuthItemsCreateRoute
  '/items/list': typeof AuthItemsListRoute
  '/products/create': typeof AuthProductsCreateRoute
  '/products/list': typeof AuthProductsListRoute
  '/sales/create': typeof AuthSalesCreateRoute
  '/sales/list': typeof AuthSalesListRoute
  '/items/edit/$itemId': typeof AuthItemsEditItemIdRoute
  '/products/edit/$productId': typeof AuthProductsEditProductIdRoute
}

export interface FileRoutesByTo {
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthDashboardRoute
  '/items/create': typeof AuthItemsCreateRoute
  '/items/list': typeof AuthItemsListRoute
  '/products/create': typeof AuthProductsCreateRoute
  '/products/list': typeof AuthProductsListRoute
  '/sales/create': typeof AuthSalesCreateRoute
  '/sales/list': typeof AuthSalesListRoute
  '/items/edit/$itemId': typeof AuthItemsEditItemIdRoute
  '/products/edit/$productId': typeof AuthProductsEditProductIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/items/create': typeof AuthItemsCreateRoute
  '/_auth/items/list': typeof AuthItemsListRoute
  '/_auth/products/create': typeof AuthProductsCreateRoute
  '/_auth/products/list': typeof AuthProductsListRoute
  '/_auth/sales/create': typeof AuthSalesCreateRoute
  '/_auth/sales/list': typeof AuthSalesListRoute
  '/_auth/items/edit/$itemId': typeof AuthItemsEditItemIdRoute
  '/_auth/products/edit/$productId': typeof AuthProductsEditProductIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/dashboard'
    | '/items/create'
    | '/items/list'
    | '/products/create'
    | '/products/list'
    | '/sales/create'
    | '/sales/list'
    | '/items/edit/$itemId'
    | '/products/edit/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/login'
    | '/dashboard'
    | '/items/create'
    | '/items/list'
    | '/products/create'
    | '/products/list'
    | '/sales/create'
    | '/sales/list'
    | '/items/edit/$itemId'
    | '/products/edit/$productId'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/dashboard'
    | '/_auth/items/create'
    | '/_auth/items/list'
    | '/_auth/products/create'
    | '/_auth/products/list'
    | '/_auth/sales/create'
    | '/_auth/sales/list'
    | '/_auth/items/edit/$itemId'
    | '/_auth/products/edit/$productId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/login"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/dashboard",
        "/_auth/items/create",
        "/_auth/items/list",
        "/_auth/products/create",
        "/_auth/products/list",
        "/_auth/sales/create",
        "/_auth/sales/list",
        "/_auth/items/edit/$itemId",
        "/_auth/products/edit/$productId"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_auth/dashboard": {
      "filePath": "_auth.dashboard.tsx",
      "parent": "/_auth"
    },
    "/_auth/items/create": {
      "filePath": "_auth.items.create.tsx",
      "parent": "/_auth"
    },
    "/_auth/items/list": {
      "filePath": "_auth.items.list.tsx",
      "parent": "/_auth"
    },
    "/_auth/products/create": {
      "filePath": "_auth.products.create.tsx",
      "parent": "/_auth"
    },
    "/_auth/products/list": {
      "filePath": "_auth.products.list.tsx",
      "parent": "/_auth"
    },
    "/_auth/sales/create": {
      "filePath": "_auth.sales.create.tsx",
      "parent": "/_auth"
    },
    "/_auth/sales/list": {
      "filePath": "_auth.sales.list.tsx",
      "parent": "/_auth"
    },
    "/_auth/items/edit/$itemId": {
      "filePath": "_auth.items.edit.$itemId.tsx",
      "parent": "/_auth"
    },
    "/_auth/products/edit/$productId": {
      "filePath": "_auth.products.edit.$productId.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
